name: phoenix_socket
description: >-
  PhoenixSocket provides a feature-complete implementation
  of Phoenix Sockets, using a single API based on StreamChannels
  compatible with any deployment of Flutter.
version: 0.4.11
repository: https://www.github.com/matehat/phoenix-socket-dart
homepage: https://www.github.com/matehat/phoenix-socket-dart

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  equatable: ^2.0.0
  quiver: ^3.0.0
  logging: ^1.0.0
  pedantic: ^1.11.0
  meta: ^1.3.0
  web_socket_channel: ^2.0.0
  rxdart: ^0.26.0

dev_dependencies:
  very_good_analysis: ^2.0.0
  test: ^1.16.5
